import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  NotificationSeverity,
  NotificationType,
  UserRole,
  type Notification,
} from '@prisma/client';
import { Transform, Type } from 'class-transformer';
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Max,
  Min,
  ValidateIf,
} from 'class-validator';
import { TrimString } from '../../../common/transformers/normalize';
import { PaginationQueryDto } from '../../../common/dto/pagination.dto';

/**
 * An administrator announcement. Reminder notifications are generated by the
 * sweep rather than sent by hand, so only ANNOUNCEMENT can be created here.
 */
export class CreateAnnouncementDto {
  @ApiProperty({ example: 'Gym closed for maintenance on Sunday' })
  @TrimString()
  @IsString()
  @Length(2, 160)
  title!: string;

  @ApiProperty({ example: 'The gym will be shut all day Sunday 12 October.' })
  @TrimString()
  @IsString()
  @Length(2, 4000)
  body!: string;

  @ApiPropertyOptional({
    enum: NotificationSeverity,
    enumName: 'NotificationSeverity',
    default: NotificationSeverity.INFO,
  })
  @IsOptional()
  @IsEnum(NotificationSeverity, { message: 'severity must be INFO, WARNING or CRITICAL' })
  severity?: NotificationSeverity;

  @ApiPropertyOptional({
    enum: UserRole,
    enumName: 'UserRole',
    isArray: true,
    description: 'Send to every active account with one of these roles. Omit when using userIds.',
  })
  @ValidateIf((dto: CreateAnnouncementDto) => !dto.userIds || dto.userIds.length === 0)
  @IsArray()
  @ArrayMaxSize(3)
  @IsEnum(UserRole, { each: true, message: 'roles must contain only ADMIN, TRAINER or MEMBER' })
  roles?: UserRole[];

  @ApiPropertyOptional({
    format: 'uuid',
    isArray: true,
    description: 'Send to specific accounts. Takes precedence over roles.',
  })
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(500)
  @IsUUID('4', { each: true, message: 'userIds must contain valid UUIDs' })
  userIds?: string[];
}

export class QueryNotificationsDto extends PaginationQueryDto {
  @ApiPropertyOptional({ description: 'true for unread only, false for read only' })
  @IsOptional()
  @Transform(({ value }: { value: unknown }) =>
    value === 'true' ? true : value === 'false' ? false : value,
  )
  @IsBoolean({ message: 'unread must be true or false' })
  unread?: boolean;

  @ApiPropertyOptional({ enum: NotificationType, enumName: 'NotificationType' })
  @IsOptional()
  @IsEnum(NotificationType, { message: 'type must be a known notification type' })
  type?: NotificationType;
}

export class RunRemindersDto {
  @ApiPropertyOptional({
    example: 7,
    minimum: 1,
    maximum: 90,
    default: 7,
    description: 'How many days ahead to warn about a membership about to lapse',
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(90)
  expiringWithinDays: number = 7;

  @ApiPropertyOptional({
    example: 0.01,
    minimum: 0,
    description: 'Only remind members owing at least this much',
  })
  @IsOptional()
  @Type(() => Number)
  @Min(0)
  minimumBalance?: number;
}

export class NotificationResponseDto {
  @ApiProperty({ format: 'uuid' }) id!: string;
  @ApiProperty({ enum: NotificationType, enumName: 'NotificationType' })
  type!: NotificationType;
  @ApiProperty({ enum: NotificationSeverity, enumName: 'NotificationSeverity' })
  severity!: NotificationSeverity;
  @ApiProperty({ example: 'Your membership expires in 3 days' }) title!: string;
  @ApiProperty() body!: string;
  @ApiPropertyOptional({ nullable: true, example: 'membership' })
  relatedEntityType!: string | null;
  @ApiPropertyOptional({ format: 'uuid', nullable: true }) relatedEntityId!: string | null;
  @ApiProperty({ example: false }) read!: boolean;
  @ApiPropertyOptional({ type: String, format: 'date-time', nullable: true })
  readAt!: Date | null;
  @ApiProperty({ type: String, format: 'date-time' }) createdAt!: Date;

  static from(notification: Notification): NotificationResponseDto {
    return {
      id: notification.id,
      type: notification.type,
      severity: notification.severity,
      title: notification.title,
      body: notification.body,
      relatedEntityType: notification.relatedEntityType,
      relatedEntityId: notification.relatedEntityId,
      read: notification.readAt !== null,
      readAt: notification.readAt,
      createdAt: notification.createdAt,
    };
  }
}

export class UnreadCountDto {
  @ApiProperty({ example: 3 }) unread!: number;
}

export class ReminderRunDto {
  @ApiProperty({ example: 12, description: 'Membership-expiry reminders created' })
  expiringMemberships!: number;
  @ApiProperty({ example: 4, description: 'Reminders for memberships that have just lapsed' })
  expiredMemberships!: number;
  @ApiProperty({ example: 7, description: 'Payment reminders created' })
  paymentReminders!: number;
  @ApiProperty({
    example: 23,
    description: 'Reminders skipped because the same one already exists',
  })
  skippedAsDuplicate!: number;
}

export class BulkResultDto {
  @ApiProperty({ example: 18 }) affected!: number;
}
