import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  ParseUUIDPipe,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiCreatedResponse,
  ApiForbiddenResponse,
  ApiNoContentResponse,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiProperty,
  ApiTags,
} from '@nestjs/swagger';
import { UserRole } from '@prisma/client';
import { SWAGGER_TAGS } from '../../common/swagger/swagger.setup';
import { ApiErrorResponse } from '../../common/dto/api-error.dto';
import { PaginationMeta } from '../../common/dto/pagination.dto';
import { Roles, ScopedAccess } from '../auth/decorators/roles.decorator';
import { CurrentUser } from '../auth/decorators/current-user.decorator';
import { AuditAction } from '../audit/audit.decorator';
import { NotificationsService } from './notifications.service';
import {
  BulkResultDto,
  CreateAnnouncementDto,
  NotificationResponseDto,
  QueryNotificationsDto,
  ReminderRunDto,
  RunRemindersDto,
  UnreadCountDto,
} from './dto/notification.dto';

export class PaginatedNotificationsDto {
  @ApiProperty({ type: [NotificationResponseDto] }) data!: NotificationResponseDto[];
  @ApiProperty({ type: PaginationMeta }) meta!: PaginationMeta;
}

/**
 * In-app notifications.
 *
 * Every read and write is scoped to the signed-in user inside the query, so
 * there is no id a caller could supply to reach somebody else's messages.
 */
@ApiTags(SWAGGER_TAGS.notifications)
@ApiBearerAuth('access-token')
@ApiForbiddenResponse({ description: 'Role not permitted', type: ApiErrorResponse })
@Controller({ path: 'notifications' })
export class NotificationsController {
  constructor(private readonly notifications: NotificationsService) {}

  // --- Fixed paths before /:id ---

  @ScopedAccess('Scoped to the signed-in user: no id reaches another account.')
  @Get()
  @ApiOperation({
    summary: 'Own notifications',
    description: 'Newest first. Filterable by read state and type.',
  })
  @ApiOkResponse({ type: PaginatedNotificationsDto })
  async findOwn(
    @CurrentUser('id') userId: string,
    @Query() query: QueryNotificationsDto,
  ): Promise<PaginatedNotificationsDto> {
    const result = await this.notifications.findForUser(userId, query);
    return {
      data: result.data.map((notification) => NotificationResponseDto.from(notification)),
      meta: result.meta,
    };
  }

  @ScopedAccess('Scoped to the signed-in user: no id reaches another account.')
  @Get('unread-count')
  @ApiOperation({ summary: 'Number of unread notifications', description: 'For a badge.' })
  @ApiOkResponse({ type: UnreadCountDto })
  async unreadCount(@CurrentUser('id') userId: string): Promise<UnreadCountDto> {
    return { unread: await this.notifications.unreadCount(userId) };
  }

  @ScopedAccess('Scoped to the signed-in user: no id reaches another account.')
  @Post('read-all')
  @HttpCode(HttpStatus.OK)
  @AuditAction('notifications.readAll')
  @ApiOperation({ summary: 'Mark every notification read' })
  @ApiOkResponse({ type: BulkResultDto })
  async markAllRead(@CurrentUser('id') userId: string): Promise<BulkResultDto> {
    return { affected: await this.notifications.markAllRead(userId) };
  }

  @Post('announcements')
  @Roles(UserRole.ADMIN)
  @AuditAction('notifications.announce')
  @ApiOperation({
    summary: 'Send an announcement',
    description:
      'To named accounts, or to every active account with the given roles. ' +
      'Reminders are generated by the sweep, not sent by hand.',
  })
  @ApiCreatedResponse({ type: BulkResultDto })
  async announce(@Body() dto: CreateAnnouncementDto): Promise<BulkResultDto> {
    return { affected: await this.notifications.announce(dto) };
  }

  @Post('run-reminders')
  @HttpCode(HttpStatus.OK)
  @Roles(UserRole.ADMIN)
  @AuditAction('notifications.runReminders')
  @ApiOperation({
    summary: 'Generate membership and payment reminders',
    description:
      'Idempotent: every reminder carries a dedupe key, so running twice in a ' +
      'day creates nothing the second time. Intended for a schedule.',
  })
  @ApiOkResponse({ type: ReminderRunDto })
  runReminders(@Body() dto: RunRemindersDto): Promise<ReminderRunDto> {
    return this.notifications.runReminders(dto);
  }

  @ScopedAccess('Scoped to the signed-in user: no id reaches another account.')
  @Post(':id/read')
  @HttpCode(HttpStatus.OK)
  @AuditAction('notifications.read')
  @ApiOperation({ summary: 'Mark one notification read' })
  @ApiOkResponse({ type: NotificationResponseDto })
  @ApiNotFoundResponse({ description: 'Not one of yours', type: ApiErrorResponse })
  async markRead(
    @CurrentUser('id') userId: string,
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<NotificationResponseDto> {
    return NotificationResponseDto.from(await this.notifications.markRead(userId, id));
  }

  @ScopedAccess('Scoped to the signed-in user: no id reaches another account.')
  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @AuditAction('notifications.remove')
  @ApiOperation({ summary: 'Dismiss a notification' })
  @ApiNoContentResponse({ description: 'Dismissed' })
  @ApiNotFoundResponse({ description: 'Not one of yours', type: ApiErrorResponse })
  async remove(
    @CurrentUser('id') userId: string,
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<void> {
    await this.notifications.remove(userId, id);
  }
}
